WIP Get state of PR.
GIT_MULTI_BRANCH=_git-multi-pr--get-state-of-8C36EB07-44C0-4F3E-9BB8-8F3D741BC629
PR=76

diff --git a/git-multi-pr b/git-multi-pr
--- a/git-multi-pr
+++ b/git-multi-pr
@@ -128,6 +128,7 @@ sync_queue() {
   git fetch --all --prune &>/dev/null
   git rebase "origin/$master"
 
+  # TODO: Only cleanup if flag is passed in.
   echo
   cleanup
 }
@@ -604,10 +605,6 @@ _get_ref_pr_number() {
 }
 
 submit_pr() {
-  echo "${bold}First re-exporting your local queue.${normal}"
-  echo
-  export_prs
-
   local refs="$(_git_get_commits --reverse)"
   local IFS=$'\n' refs_array=($refs)
   local ref="${refs_array[0]}"
@@ -647,6 +644,57 @@ submit_pr() {
       return 1
       ;;
   esac
+}
+
+_get_pr_status() {
+  # open, pending (submitting), closed (dropped), merged (submitted), missing (never created), unknown (network down)
+
+  local number="$1"
+
+  local repo_org="$(_get_repo_org)"
+  local repo_name="$(_get_repo_name)"
+  local filter
+  local response
+
+  # Unknown
+  _ensure_github_permissions || {
+    echo "unknown"
+    return
+  }
+
+  # Missing
+  ok.sh _get "/repos/$repo_org/$repo_name/pulls/$number" &>/dev/null || {
+    echo "missing"
+    return
+  }
+
+  # Merged
+  ok.sh _get "/repos/$repo_org/$repo_name/pulls/$number/merge" &>/dev/null && {
+    echo "merged"
+    return
+  }
+
+  # Closed
+  filter='"\(.state)"'
+  response="$(ok.sh _get "/repos/$repo_org/$repo_name/pulls/$number" | ok.sh _filter_json "$filter")"
+  if [[ "$response" == "closed" ]]; then
+    echo "closed"
+    return
+  fi
+
+  # Pending
+  filter='.[] | "\(.body)"'
+  response="$(ok.sh _get "/repos/$repo_org/$repo_name/issues/$number/comments" | ok.sh _filter_json "$filter")"
+  local dash="$(printf '\xf0\x9f\x92\xa8\x0a')"
+  local rocket="$(printf '\xf0\x9f\x9a\x80\x0a')"
+  for $comment in $response; do
+    if [[ "$comment" == *"$dash"* ]] || [[ "$comment" == *"$rocket"* ]]; then
+      echo "pending"
+      return
+    fi
+  done
+
+  # Open
 }
 
 _git_get_branch() {
@@ -735,6 +783,7 @@ case "$1" in
   _get_repo_org)                        _get_repo_org "${@:2}" ;;
   _get_repo_name)                       _get_repo_name "${@:2}" ;;
   _ensure_github_permissions)           _ensure_github_permissions "${@:2}" ;;
+  _get_pr_status)                       _get_pr_status "${@:2}" ;;
 
 
   # Help
